- .gitignore
- conf/patient.conf.js
- pages/geolocationPage.js
- pages/landingPage.js
- pages/loginPage.js
- pages/patient/my_account/allergiesPage.js
- pages/patient/my_account/medicationsPage.js
- pages/patient/my_account/personalInfoPage.js
- tests/my_account/health_records_test.js
- tests/my_account/personal_info.js
This change will add the new medication test and improve overall performance of PageObject based tests.
> Ticket #251354 - Medication settings page

- pages/patient/geolocationPage.js
- pages/patient/landingPage.js
- pages/patient/my_account/allergiesPage.js
- pages/patient/my_account/conditionsPage.js
- pages/patient/my_account/familyHistoryPage.js
- pages/patient/my_account/medicationsPage.js
- pages/patient/my_account/personalInfoPage.js
- pages/patient/my_account/proceduresPage.js
- pages/patient/my_account/questionnairePage.js
- pages/patient/my_account/settingsPage.js
- tests/patient/my_account/health_records_test.js
This PR include new tests to the health records module. Also, it will move the location of some files and the refactoring needed because of this.
> Ticket #25135h - Add questionnaire tests

- commands/clearValue2.js
- pages/patient/geolocationPage.js
- pages/patient/landingPage.js
- pages/patient/my_account/paymentMethodPage.js
- tests/patient/my_account/payment-method_test.js
This PR includes changes in the clearValue custom function to improve performance and the new payment method test.
> Ticket #25135m - Payment method test

- pages/patient/my_account/personalInfoPage.js
- pages/patient/my_account/pharmacyPage.js
- pages/patient/my_account/settingsPage.js
- tests/patient/my_account/personal_info.js
- tests/patient/my_account/pharmacy.js
This PR includes the following tests for Pharmacy:
- Check if the search address of Pharmacy page has the address inputted by patient
- Search a new address and select pharmacy selecting on the **list**
- Search a new address and select pharmacy selecting on the **map**
> Ticket #25135j - Add tests for Pharmacy search and update

- conf/patient.conf.js
- conf/provider.conf.js
- pages/loginPage.js
- pages/provider/schedulerPage.js
- pages/provider/waitingRoomPage.js
- tests/provider/scheduler_test.js
This PR will change how the login page works to now also accept providers and will add the schedule test for providers adding a visit for a existing patient.
> Ticket #cyu2wv - schedule visit for existing patient

- pages/patient/geolocationPage.js
- pages/provider/schedulerPage.js
- tests/provider/scheduler_test.js
This PR will add the new test and also refactor the previous scheduling tests to improve confiability.
> Ticket #cyu2yc - Edit Scheduling

- pages/provider/my_account/personalInfoPage.js
- pages/provider/waitingRoomPage.js
- tests/provider/my_account/personal_info.js
Add the Edit Personal Info on provider account, very similar to the existent for the patient. 
I decided to maintain the timezone in order to not interfere in the scheduling tests.
> Ticket #2czvmp - Add test - Edit Provider Personal Info

- commands/clearValue2.js
- pages/loginPage.js
- pages/patient/landingPage.js
- pages/patient/my_account/conditionsPage.js
- pages/patient/my_account/familyHistoryPage.js
- pages/patient/my_account/insurancePage.js
- pages/patient/my_account/medicationsPage.js
- pages/patient/my_account/paymentMethodPage.js
- pages/patient/my_account/personalInfoPage.js
- pages/patient/my_account/pharmacyPage.js
- pages/patient/my_account/proceduresPage.js
- pages/patient/my_account/questionnairePage.js
- pages/patient/my_account/settingsPage.js
- pages/provider/my_account/personalInfoPage.js
- pages/provider/schedulerPage.js
- tests/patient/my_account/health_records_test.js
This PR includes:
- replacing `patientLogin` and `providerLogin` to `userLogin`
- removing unnecessary `self` references
- refactoring `clearValue` command
- refactoring `landingPage`
- resolving conflict with `checkToastMessage`
> Ticket #2czxdg - Refactoring login, landingPage, clearValue and removing self references

- commands/editTextField.js
- conf/patient.conf.js
- conf/provider.conf.js
- pages/loginPage.js
- pages/patient/first_time_login/insurancePage.js
- pages/patient/first_time_login/personalInfoPage.js
- pages/patient/first_time_login/profilePicturePage.js
- pages/patient/first_time_login/welcomePage.js
- pages/patient/geolocationPage.js
- tests/patient/registration_test.js
- Remove unnecessary wait time in text edit;
- Update patient.conf and provider.conf to use new password and added geolocation capabilities
- Add all necessary files for the registration tests
> Ticket #2d45av - Registration tests

- conf/patient.conf.js
- conf/provider.conf.js
- pages/patient/my_account/settingsPage.js
- tests/provider/my_account/settings.js
This test includes:
- Change email
- Change password
- Check changes with a new login
- Revert changes in order to not affect other tests
> Ticket #2d2nat: Add test - Edit Provider Settings

- conf/patient.conf.js
- conf/provider.conf.js
- pages/loginPage.js
- pages/patient/landingPage.js
- pages/provider/waitingRoomPage.js
- tests/patient/help-equipment_test.js
- tests/patient/login-logout_test.js
- tests/provider/login-logout_test.js
- Update provider.conf.js and patient.conf.js accordingly to other PRs;
- Add login and logout tests for both patient and provider;
- Add 'Help' modal test to check links;
- Add 'Equipment Test' link test to check if the link can be opened;
> Ticket #2d7ctq and #2ezxq1 - Login, logout,help,equipment tests

- pages/loginPage.js
A few lines of code on this method ended up mixing up with lines of another method in this page during merge conflict fixing
> Fix for registrationFailureDifferentPasswords

- conf/provider.conf.js
- pages/patient/my_account/settingsPage.js
- pages/provider/my_account/notificationsPage.js
- tests/patient/my_account/settings_notifications.js
- tests/provider/my_account/notifications_test.js
This PR includes the following tests of (Provider) My Account > Notifications:
- Edit notification channels
- Toggle on/off notification channels
- Add new notification channels of each type
- Remove notification channel
- Change "Notify Me When..." options
- Change "Notify My Patients..." options
- Save all changes and check the persistence after logout
**Note:**  the tests of "Notify Me When..." are failing due to an existent issue mentioned in [this ticket](https://app.clickup.com/t/9rn25y).
**Note 2:** Due to that issue, I modified the `conf/provider.conf.js` to include a flag that allows other tests to run even with those failed ones, otherwise they would be skipped.
The PR also includes an update of Patient Notifications Tests to include a workaround to check the persistence of …
> Ticket #2d4bbf - Provider Notifications Tests

- pages/patient/my_account/allergiesPage.js
- pages/provider/my_account/biographyPage.js
- tests/patient/my_account/health_records_test.js
- tests/provider/my_account/biography_test.js
- Added new biography tests for both ‘Bio Generator’ and ‘HTML Editor’.
- Added new general allergies and medication allergies tests for patients.
> Ticket #2f0vn0 / #51353 - Provider Biography Tests and Patient allergy settings

- pages/provider/PatientsPage.js
- pages/provider/waitingRoomPage.js
- tests/provider/patients_test.js
- Add tests for the patients tab and all patient sidebar options
> Ticket #2f3cwj - Patients Tab tests

- conf/patient.conf.js
- pages/patient/first_time_login/insurancePage.js
- pages/patient/first_time_login/personalInfoPage.js
- pages/patient/first_time_login/welcomePage.js
- pages/patient/my_account/allergiesPage.js
- pages/patient/my_account/conditionsPage.js
- pages/patient/my_account/familyHistoryPage.js
- pages/patient/my_account/insurancePage.js
- pages/patient/my_account/medicationsPage.js
- pages/patient/my_account/proceduresPage.js
- pages/patient/my_account/questionnairePage.js
- tests/patient/currentpatient-myaccount-menucheck_test.js
- tests/patient/newpatientenrollment-requestvisit_test.js
- tests/patient/requestvisit-currentpatient_test.js
- tests/patient/self-schedule.js
Add several improvments in the way the tests behave during execution of full suite
> Small fixes and improvements on previous tests

- pages/patient/first_time_login/insurancePage.js
- pages/patient/my_account/insurancePage.js
- pages/patient/visit_history/visitHistoryPage.js
- tests/patient/visit_history/visit-history_test.js
- tests/provider/patients_test.js
- tests/provider/visit-history_test.js
added phone number format to tests that use a number check. ex: 555-555-5555
> added format to tests that use phone numbers

- tests/patient/registration_test.js
this was the remove the profile picture page from the registration flow. this was causing the test to break.
> remove profile picture from registration flow

- conf/patient.conf.js
- pages/patient/first_time_login/insurancePage.js
- pages/patient/first_time_login/personalInfoPage.js
- pages/patient/geolocationPage.js
- tests/patient/registration_test.js
- removed patient profile flow from registration
- minor verbiage changes
- bumped chrome version to latest
> fix borked patient registration tests

- conf/suite.conf.js
Combined patient and provider configuration files. Implemented common capability support.
> combine configs files. add common capabilities

- tests/patient/forgot-password_test.js
- tests/patient/help-equipment_test.js
- tests/patient/login-logout_test.js
- tests/patient/my_account/health_records_test.js
- tests/patient/my_account/insurance_test.js
- tests/patient/my_account/payment-method_test.js
- tests/patient/my_account/personal_info.js
- tests/patient/my_account/pharmacy.js
- tests/patient/my_account/settings_account_details.js
- tests/patient/my_account/settings_notifications_test.js
- tests/patient/registration_test.js
- tests/patient/visit_history/visit-history_test.js
- tests/provider/login-logout_test.js
- tests/provider/my_account/availability_test.js
- tests/provider/my_account/biography_test.js
- tests/provider/my_account/notifications_test.js
- tests/provider/my_account/personal_info.js
- tests/provider/my_account/settings_test.js
- tests/provider/patients_test.js
- tests/provider/scheduler_test.js
- tests/provider/visit-history_test.js
Remove beforeEach methods that are now stored as a common capabilities
> remove beforeEach methods from tests

- .gitignore
- conf/canary.conf.js
- node_modules/.package-lock.json
- package-lock.json
- package.json
Update canary command
Update chromedriver
ignore nightwatch.conf
> Canary system update
